export const posts = [
  {
    id: 1,
    title: "A Day at the Beach",
    body: "Sun, sand, and seagulls. What a perfect day!",
    author: "Sarah",
    color: "#FF0000",
    isLiked: true,
  },
  {
    id: 2,
    title: "My Favorite Recipe",
    body: "Here's my secret recipe for the best chocolate chip cookies.",
    author: "David",
    color: "#00FF00",
    isLiked: false,
  },
  {
    id: 3,
    title: "Hiking Adventure",
    body: "Just finished a 10-mile hike. My legs are burning!",
    author: "Emily",
    color: "#0000FF",
    isLiked: true,
  },
  {
    id: 4,
    title: "Book Review",
    body: "I just finished reading 'The Great Gatsby.' What a fantastic book!",
    author: "Ben",
    color: "#FFFF00",
    isLiked: false,
  },
  {
    id: 5,
    title: "Travel Tips",
    body: "My top tips for planning a budget-friendly vacation.",
    author: "Chris",
    color: "#800080",
    isLiked: true,
  },
  {
    id: 6,
    title: "Funny Cat Videos",
    body: "Check out these hilarious cat videos. They'll make your day!",
    author: "Alex",
    color: "#FFA500",
    isLiked: true,
  },
  {
    id: 7,
    title: "Gardening Tips",
    body: "How to grow the perfect tomato plant.",
    author: "Olivia",
    color: "#008000",
    isLiked: false,
  },
  {
    id: 8,
    title: "Movie Review",
    body: "I just saw the new Marvel movie. It was amazing!",
    author: "Michael",
    color: "#00FFFF",
    isLiked: true,
  },
  {
    id: 9,
    title: "Technology News",
    body: "The latest tech news and trends.",
    author: "Ethan",
    color: "#FFC0CB",
    isLiked: false,
  },
  {
    id: 10,
    title: "DIY Projects",
    body: "How to build your own bookshelf.",
    author: "Lisa",
    color: "#808080",
    isLiked: true,
  },
  {
    id: 11,
    title: "Cooking Challenge",
    body: "Let's see who can make the best homemade pizza.",
    author: "Emily",
    color: "#0000FF",
    isLiked: true,
  },
  {
    id: 12,
    title: "Travel Photography",
    body: "My favorite travel photos from my recent trip to Europe.",
    author: "Sarah",
    color: "#FF0000",
    isLiked: false,
  },
  {
    id: 13,
    title: "Book Club Discussion",
    body: "What did you think of the latest book we read?",
    author: "Ben",
    color: "#FFFF00",
    isLiked: true,
  },
  {
    id: 14,
    title: "Game Night",
    body: "Let's get together for a fun game night.",
    author: "David",
    color: "#00FF00",
    isLiked: false,
  },
  {
    id: 15,
    title: "DIY Skincare Tips",
    body: "How to make your own natural skincare products.",
    author: "Olivia",
    color: "#008000",
    isLiked: true,
  },
];
